spring:
  application:
    name: eureka-server
---
spring:
  profiles: peer1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

server:
  port: 8080

---

spring:
  profiles: peer2

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

server:
  port: 8081